{
    "input": {
        "event": {
            "created": "2019-04-12T09:14:32.287Z",
            "id": "10f0afe9-98a1-4226-a6bd-8f70d461d430"
        },
        "log": {
            "hostname": "fame"
        },
        "message": " error: maximum authentication attempts exceeded for invalid user support from sshbot.irmhill.xyz port 51219 ssh2 [preauth]"
    },
    "expected": {
        "event": {
            "created": "2019-04-12T09:14:32.287Z",
            "id": "10f0afe9-98a1-4226-a6bd-8f70d461d430"
        },
        "log": {
            "hostname": "fame"
        },
        "message": " error: maximum authentication attempts exceeded for invalid user support from sshbot.irmhill.xyz port 51219 ssh2 [preauth]",
        "action": {
            "outcome_reason": "maximum authentication attempts exceeded",
            "type": "open",
            "name": "connection",
            "outcome": "failure",
            "target": "user"
        },
        "source": {
            "user": {
                "name": "support"
            },
            "domain": "sshbot.irmhill.xyz",
            "address": "sshbot.irmhill.xyz",
            "port": 51219,
            "size_in_char": 18
        },
        "user": {
            "name": "support"
        },
        "related": {
            "user": [
                "support"
            ]
        },
        "type": "kafka",
        "sekoiaio": {
            "intake": {
                "parsing_status": "success"
            }
        },
        "host": {
            "hostname": "fame",
            "name": "fame"
        }
    }
}